# Import packages.
import pandas as pd
import plotly.express as px
import streamlit as st

# Read in supporting functions from the same directory.
import chat_agent
import data_models

# Some tech debt in the next 3 functions -- prompts should be moved to chat_agent for consolidated management of prompts.

def identify_domains(user_input):
	"""
	Identify relevant domains based on user input.

		Args:
			user_input: the user's input to the chat agent.

		Returns:
			A list of relevant skill domains.
	"""

	domains = ', '.join(list(taxonomy.keys()))
	domain_prompt = f"Find 3 domains relevant to the following statement: {user_input}. You MUST select from these domains, and CANNOT make up your own: {domains}"
	chat_agent.update_conversation(domain_prompt, role='user')
	return chat_agent.chatgpt(format_=data_models.DomainsClass).name

def select_subjects(user_input, domain_response):
	"""
	Identify relevant subjects based on the selected domains.

		Args:
			user_input: the user's input to the chat agent.
			domain_response: the domains that were selected.

		Returns:
			A list of relevant subjects.
	"""
	subjects = ', '.join([', '.join(taxonomy[domain].keys()) for domain in taxonomy.keys() if domain in domain_response])
	#subjects = ', '.join([taxonomy[domain].keys() for domain in taxonomy.keys() if domain in domain_response])
	subjects_prompt = f"Find 10-15 subjects relevant to the following statement: {user_input}. You MUST select from these subjects, and CANNOT make up your own. Select at least 2 subjects for each domain: {subjects}"
	chat_agent.update_conversation(subjects_prompt, role='user')
	return chat_agent.chatgpt(format_=data_models.SubjectsClass).name

def curate_skills(user_input, domain_response, subject_response):
	"""
	Identify relevant subjects based on the selected domains.

		Args:
			user_input: the user's input to the chat agent.
			domain_response: the domains that were selected.
			subject_response: the subjects that were selected.

		Returns:
			A list of relevant skills.
	"""	
	skills = ', '.join(skill for domain in taxonomy.keys() if domain in domain_response for subject in taxonomy[domain] if subject in subject_response for skill in taxonomy[domain][subject])
	skills_prompt = f"Find 20-40 skills relevant to the following statement: {user_input}. You MUST select from these skills, and CANNOT make up your own. Select at least two skills for each subject: {skills}"
	chat_agent.update_conversation(skills_prompt, role='user')
	return chat_agent.chatgpt(format_=data_models.SkillsClass).name

def generate_sunburst(data):
	"""
	Turn the curated taxonomy data into a sunburst visualization.

		Args:
			data: the taxonomy data to visualize.

		
		Returns:
			Plotly sunburst visualization.
	"""
	# Define labels and parents as non-local variables to accumulate across recursive calls
	labels = []
	parents = []

	def parse_dict(data, current_parent=None):
		"""
		Recursve function to handle transforming the data into the correct shape for
		the sunburst visualization.

			Args:
				data: the taxonomy data to visualize.
				current_parent: the current parent label in the domain>subject>skill taxonomy chain.

			Returns:
				Updates the lists for `labels` and `parents` to be handled for the data visualization.
		"""
		for key, value in data.items():
			labels.append(key)
			parents.append(current_parent if current_parent else "")
			if isinstance(value, dict):
				parse_dict(value, key)  # Recursive call: pass the current key as the parent for nested items.
			elif isinstance(value, list):
				for item in value:
					labels.append(item)
					parents.append(key)

	# Parse the data dictionary.
	parse_dict(data)

	# Create a sunburst chart
	fig = px.sunburst(
		names=labels,
		parents=parents,
		title="Relevant skills"
	)

	# Adjust the figure size
	fig.update_layout(width=800, height=800)

	# Render the chart in Streamlit
	st.plotly_chart(fig, use_container_width=True, theme=None)


def generate_sunburst_tableview(data):

	"""
	Flatten the taxonomy data into a pandas DataFrame.
	This used to be shown to the user, but the function is reserved to
	pass the context of the table around in the prototype (a decision could
	be made that this is redundant, and that it is sufficient to keep it in 
	its python dictionary data structure).

		Args:
			data: the taxonomy data.

		Returns:
			A pandas DataFrame of the data.
	"""

	# Initialize lists to hold the data
	top_keys = []
	middle_keys = []
	skills = []

	# Process the nested dictionary
	for top_key, subjects in data.items():
		for middle_key, skill_list in subjects.items():
			for skill in skill_list:
				# Fill top_keys with the same value for the length of skill_list
				top_keys.append(top_key)
				middle_keys.append(middle_key)
				# Fill skills, ensuring all skills are captured and None where necessary
				skills.append(skill)
			
	df = pd.DataFrame({
		'Skill': skills,
		'Subject': middle_keys,
		'Domain': top_keys
	})

	return df

def prune_taxonomy(domains_list, subjects_list, skills_list, taxonomy):
	"""
	Sometimes OpenAI identifies domains and subjects that are dead ends -- they don't have any
	skills that are also identified. This prunes the taxonomy to remove any dead end domains and subjects.

		Args:
			domains_list: A list of Udacity skill domains.
			subjects_list: A list of Udacity skill subjects.
			skills_list: A list of Udacity skills.
			taxonomy: The full Udacity taxonomy.

		Returns:
			Curated taxonomy, pruned of dead end domains and subjects.
	"""

   # For storing results.
	pruned_taxonomy = {}

	for domain in domains_list:

		if domain in taxonomy:
			# Initialize a dictionary for valid subjects within this domain
			valid_subjects = {}
			
			for subject in subjects_list:
				if subject in taxonomy[domain]:
					# Find the skills within the subject
					skills_in_subject = [
						skill for skill in skills_list if skill in taxonomy[domain][subject]
					]
					# Add the subject only if it has skills
					if skills_in_subject:
						valid_subjects[subject] = skills_in_subject
			
			# Add the domain only if it has valid subjects
			if valid_subjects:
				pruned_taxonomy[domain] = valid_subjects
				
	# Return final taxonomy.
	return pruned_taxonomy

# Because the GraphQL endpoints don't have the full taxonomy, I can't utilize that
# to fetch the taxonomy. So, here is a (very long) dictionary that stores the full taxonomy
# as of 2024 Q4.
taxonomy = {
	"Artificial Intelligence and Robotics": {
		"AI and ML Applications": [
			"3D Reconstruction",
			"AI Agents",
			"AI Fraud Detection",
			"Alexa Skill Creation",
			"Alexa Skill Deployment",
			"Alexa Skills",
			"Conversational AI",
			"Deep Fakes",
			"Game Agents",
			"Image Generation",
			"Inference Engines",
			"Intelligent Agents",
			"Question Answering Systems",
			"Recommendation Engine Business Context",
			"Recommendation Engine Design",
			"Recommendation Engine Fluency",
			"Recommendation Engines",
			"Recommender System Limitations",
			"Search Applications",
			"Search Applications Business Context",
			"Signal Visualization",
			"Social Listening with ML",
			"Spam Detection",
			"Time-Series Analysis with ML",
			"Time-series Forecasting with ML",
			"Types of ML Applications",
			"Types of Recommenders",
			"Voice User Interfaces",
		],
		"AI Ethics": [
			"Voice User Interfaces",
			"AI Fairness",
			"AI Governance",
			"AI Transparency",
			"Ethical AI Awareness",
			"Ethical AI",
			"Explainable AI",
			"Microsoft Responsible AI Guidelines",
		],
		"AI for Finance": [
			"Microsoft Responsible AI Guidelines",
			"AI Credit Scoring",
			"AI Market Pricing Models",
			"Algorithmic Trading",
			"Financial Analysis with AI",
			"NLP for Finance",
		],
		"AI for Healthcare": [
			"NLP for Finance",
			"AI for 2D Medical Imaging",
			"AI for 3D Medical Imaging",
			"AI for CT Images",
			"AI in Medical Imaging",
			"AI-Assisted Cancer Detection",
			"AI-Assisted Drug Discovery",
			"AI-Assisted Genomics",
			"AI-Assisted Radiology",
			"Clinical Environment Modeling",
			"Multiplanar Reconstruction",
		],
		"AI Fundamentals": [
			"Multiplanar Reconstruction",
			"Artificial Intelligence Awareness",
			"AI Business Context",
			"AI Fluency",
			"AI Proficiency",
			"Generative AI Fluency",
			"GenAI Use Cases",
			"In-Context Learning",
			"Machine Learning Dataset Fundamentals",
			"Machine Learning Experiments",
			"Machine Learning Fluency",
			"Machine Learning Framework Fundamentals",
			"Machine Learning Lifecycle",
			"Machine Learning System Architectures",
			"Machine Learning Use Cases",
			"Prompt Engineering",
			"Symbolic AI",
		],
		"Automated Planning and Scheduling": [
			"Symbolic AI",
			"Automated Path Planning",
			"Automated Plan Optimization",
			"Automated Planning Heuristics",
			"Automated Planning Problem Definition",
			"Probabilistic Path Planning",
			"Sample-Based Path Planning",
		],
		"Computer Vision": [
			"Sample-Based Path Planning",
			"3D Object Detection",
			"Bounding Boxes",
			"Computer Vision Business Context",
			"Computer Vision Fluency",
			"Computer Vision Proficiency",
			"Computer Vision Transformers",
			"Convolutional Kernels",
			"Digital Image Keypoint Descriptors",
			"Digital Image Keypoints",
			"Face Detection",
			"Face Landmarks and Attributes",
			"Facial Recognition",
			"Form Recognition",
			"Handwriting Recognition",
			"Harris Detector",
			"Image Caption Generation",
			"Image Classification",
			"Image Pre-Processing",
			"Image Segmentation",
			"Multi-Target Object Tracking",
			"Non-Linear Motion Tracking",
			"Object Clustering",
			"Object Detection",
			"Object Recognition",
			"Object Track Score",
			"Object Track State",
			"Object Tracking",
			"Object Tracking Performance Metrics",
			"Optical Character Recognition",
			"Optical Flow in Computer Vision",
			"Point Cloud Data",
			"Point Clouds",
			"Range Imaging",
			"Semantic Image Segmentation",
			"Separable Convolutions",
			"SIFT Algorithm",
			"Single-Shot Object Detection",
			"Text Recognition",
			"YOLO Algorithm",
		],
		"Deep Reinforcement Learning": [
			"YOLO Algorithm",
			"Actor-Critic Algorithms",
			"Deep Q-Learning Algorithms",
			"Deep Q-Networks",
			"Double Deep Q-Networks",
			"Dueling Deep Q-Networks",
			"Evolutionary Algorithms",
			"Monte Carlo Policy Gradients",
			"Policy Optimization Algorithms",
			"Policy-Gradient Algorithms",
			"Prioritized Experience Replay",
			"REINFORCE Algorithm",
			"Stochastic Policy Gradients",
		],
		"Digital Signal Processing": [
			"Stochastic Policy Gradients",
			"2D Image Transforms",
			"Analog Device Control",
			"Computer Vision Image Enhancement",
			"Computer Vision Image Filtering",
			"Computer Vision Image Transformations",
			"Digital Sampling",
			"Digital Signal Filtering",
			"Digital Signal Interpolation",
			"Digital Signal Processing Proficiency",
			"Digital Signal Resampling",
			"Digital Signal Windowing",
			"Frequency Domain DSP Techniques",
			"Image Transformations",
			"Signal-to-Noise Ratio",
			"Time and Space Domain DSP Techniques",
		],
		"Machine Learning Frameworks": [
			"Time and Space Domain DSP Techniques",
			"AutoGluon",
			"Basic PyTorch",
			"Caffe",
			"Comet ML",
			"Hugging Face",
			"Hydra",
			"Machine Learning Frameworks in Python",
			"OpenAI API",
			"Parameter-Efficient Fine-Tuning",
			"PyTorch",
			"scikit-learn",
			"TensorFlow",
			"TensorFlow Dataset API",
			"TensorFlow Object Detection API",
			"TensorFlow Probability Library",
			"Together AI API",
			"XGBoost",
		],
		"Machine Learning Methods": [
			"XGBoost",
			"Automated Machine Learning",
			"Automated Model Scoring",
			"Backtesting",
			"Basic Machine Learning",
			"Cloud-Based Machine Learning",
			"Continuous Learning",
			"Continuous Model Updating",
			"Data Slicing",
			"Data Splitting",
			"Edge AI",
			"Feature Embeddings",
			"Feature Engineering",
			"Feature Importance Calculation",
			"Hyperparameter Tuning",
			"Machine Learning Data Recording",
			"Machine Learning Model Implementation",
			"Machine Learning Workflow",
			"ML Project Reporting",
			"Model Bias Analysis",
			"Model Bias Mitigation",
			"Model Documentation",
			"Model Drift",
			"Model Evaluation",
			"Model Interpretation",
			"Model Monitoring",
			"Model Score Recording",
			"Model Training",
			"Model Uncertainty Estimation",
			"Probabilistic Graphical Models",
			"Training Data Manifest Files",
		],
		"Machine Learning Pipelines": [
			"Training Data Manifest Files",
			"Data Augmentation",
			"Data Pre-Processing for ML",
			"Dataset Annotation",
			"Inference Pipelines",
			"Machine Learning Pipeline Creation",
			"Machine Learning Pipeline Fundamentals",
			"Model Deployment",
			"Model Maintenance",
			"Model Performance Metrics",
			"Model Scoring",
			"Model Testing",
			"NLP Pipelines",
		],
		"MLOps": [
			"NLP Pipelines",
			"Machine Learning Configuration Management",
			"Machine Learning Experiment Tracking",
			"Machine Learning Ops Troubleshooting",
		],
		"Natural Language Processing": [
			"Machine Learning Ops Troubleshooting",
			"Bag of Words",
			"BERT",
			"Correlated Topic Models",
			"Dynamic Topic Models",
			"Entity Recognition",
			"FastText",
			"GloVe",
			"GPT",
			"Information Extraction",
			"Information Retrieval",
			"Intent Recognition",
			"Key Phrase Extraction",
			"Latent Dirichlet Allocation",
			"Lemmatization",
			"Machine Translation",
			"Mixture of Unigrams",
			"NLP Business Context",
			"NLP Models",
			"NLP Pipelines",
			"NLP Proficiency",
			"NLP Transformers",
			"Pachinko Allocation Model",
			"Part of Speech Tagging",
			"Self-Aggregating Topic Model",
			"Sentiment Analysis",
			"Sequential Text Analysis",
			"Sparse Pseudo-Document Topic Model",
			"Speech Generation",
			"Speech Recognition",
			"Stemming",
			"Text Classification",
			"Text Generation",
			"Text Pre-Processing",
			"Text Summarization",
			"tf-idf",
			"Tokenization",
			"Topic Modeling",
			"Topics Over Time",
			"Word Embeddings",
			"Word2vec",
		],
		"Neural Networks and Deep Learning": [
			"Word2vec",
			"Attention Mechanisms",
			"Autoencoders",
			"Backpropagation",
			"Bayesian Neural Networks",
			"Capsule Networks",
			"Convolutional Neural Networks",
			"CycleGAN",
			"Deep Autoregressive Networks",
			"Deep Learning",
			"Deep Learning Applications",
			"Deep Learning Fluency",
			"Deep Learning Framework Proficiency",
			"Deep Learning Model Deployment",
			"Deep Learning Model Optimization",
			"Deep Learning Models",
			"Deep Learning Techniques",
			"Deep Learning Tools",
			"Diffusion Models",
			"Feature Matching",
			"Feature Tracking",
			"Feature Visualization",
			"Feedforward Neural Networks",
			"FLOPs",
			"Foundation Models",
			"Fully Convolutional Neural Networks",
			"Generalized Advantage Estimation",
			"Generative Adversarial Networks",
			"LangChain",
			"Large Language Models",
			"Long-Short Term Memory Networks",
			"Neural Network Activation",
			"Neural Network Basics",
			"Neural Network Initialization",
			"Neural Network Mechanics",
			"Neural Network Memory",
			"Neural Networks",
			"Parameter Quantization",
			"Retrieval-Augmented Generation",
			"Recurrent Neural Networks",
			"Region-Based Convolutional Neural Networks",
			"Training Neural Networks",
			"Transfer Learning",
			"Transformer Neural Networks",
			"U-Net",
			"Variational Autoencoders",
			"World Model Awareness",
		],
		"Reinforcement Learning": [
			"World Model Awareness",
			"Exploration-Exploitation Dilemma",
			"Model-Based Reinforcement Learning",
			"Multi-Agent Reinforcement Learning",
			"Multi-Agent Training",
			"Multi-Armed Bandit Problems",
			"Policy-Based Reinforcement Learning",
			"Q-Learning Algorithms",
			"Reinforcement Learning Applications",
			"Reinforcement Learning Fundamentals",
			"Value-Based Reinforcement Learning",
		],
		"rgrwgttre": ["Value-Based Reinforcement Learning"],
		"Robotic Process Automation": [
			"Value-Based Reinforcement Learning",
			"Attended Automations",
			"Automated Data Extraction for RPA",
			"Background Automation",
			"Basic Robotic Process Automation",
			"Process Automation Design",
			"Process Scheduling for RPA",
			"Robotic Enterprise Framework",
			"RPA Awareness",
			"RPA Best Practices",
			"RPA Business Context",
			"RPA Design Specification Documents",
			"RPA Documentation",
			"RPA Fluency",
			"RPA Process Definition Documents",
			"UI Automation for RPA",
		],
		"Robotics": [
			"UI Automation for RPA",
			"1D Object Localization",
			"1D Robot Motion Control",
			"2D Object Localization",
			"2D Robot Motion Control",
			"3D Robot Motion Control",
			"Actuators",
			"Autonomous Systems Awareness",
			"Autonomous Vehicle Fluency",
			"Bayes' Filter for Localization",
			"Bird's Eye View Maps",
			"Camera Measurement Models",
			"Collision Detection",
			"Control Algorithms",
			"Dead Reckoning",
			"Drone Flight Control",
			"Encoders",
			"Environment Mapping",
			"Environment Modeling",
			"FastSLAM",
			"GraphSLAM",
			"LiDAR Data Representation",
			"LiDAR Measurement Models",
			"LiDAR Visualization",
			"Monte Carlo Localization",
			"Motors",
			"MPC Controller",
			"Object Localization",
			"Object Motion Models",
			"Object Perturbations",
			"Object State Estimation",
			"Object State Estimation without GPS",
			"PID Controller",
			"Radar Angle of Arrival",
			"Radar Angle Resolution",
			"Radar Clutter Thresholding",
			"Radar Range Estimation",
			"Radar Range Resolution",
			"Radar Velocity Estimation",
			"Radar Velocity Resolution",
			"Robot Behavior Planning",
			"Robot Motion Planning",
			"Robot Navigation",
			"Robot Representation",
			"Robot State Management",
			"Robot Trajectory Generation",
			"Sensor Fusion",
			"Sensor Specifications",
			"Sensor Visibility Reasoning",
			"SLAM",
			"Vehicle Action",
			"Velocity Profile Generation",
		],
		"Semi-Supervised Machine Learning": ["Velocity Profile Generation"],
		"Supervised Machine Learning": [
			"Velocity Profile Generation",
			"Basic Supervised Learning",
			"Metric Learning",
			"Naive Bayes classifiers",
			"Perceptron",
			"Similarity Learning",
			"Support Vector Machines",
		],
		"Unsupervised Machine Learning": [
			"Support Vector Machines",
			"Basic Unsupervised Learning",
			"Dimensionality Reduction",
			"Evaluating Unsupervised Learning Models",
			"Feature Detection",
			"Feature Extraction",
			"Gaussian Mixture Models",
			"Hough Transforms",
			"Independent Component Analysis",
			"Principal Component Analysis",
			"Unsupervised Learning Model Deployment",
		],
	},
	"Business and Leadership": {
		"Unsupervised Machine Learning": ["Unsupervised Learning Model Deployment"],
		"Agile Project and Product Management": [
			"Unsupervised Learning Model Deployment",
			"Acceptance Criteria",
			"Agile Awareness",
			"Agile Communication",
			"Agile Fluency",
			"Agile Frameworks",
			"Agile Governance",
			"Agile Manifesto",
			"Agile Methodologies",
			"Agile Metrics",
			"Agile Velocity",
			"Backlog Grooming",
			"Backlog Management",
			"Big Visible Information Radiator",
			"Continuous Improvement",
			"Definition of Done",
			"IT Incident Postmortems",
			"Kanban",
			"Minimal Viable Products",
			"Product Backlogs",
			"Product Iteration Planning",
			"Product Release Planning",
			"Scrum",
			"Sprint Planning",
			"Sprint Retrospectives",
			"User Stories",
			"XP Framework",
		],
		"Business Intelligence and Analytics": [
			"XP Framework",
			"AARRR Metrics Framework",
			"Actionable Insight Generation",
			"Activation Metrics",
			"Ansoff Matrix",
			"Audience Behavior Tracking",
			"Behavioral Market Segmentation",
			"Business Analytics Awareness",
			"Business Analytics",
			"Business Intelligence",
			"Business KPIs",
			"Business Metrics",
			"Business Reporting Fluency",
			"Click Through Rate",
			"Cohort Analysis",
			"Content Marketing Metrics",
			"Conversion Rate",
			"Conversion Tracking",
			"Cost Per Acquisition",
			"Cost Per Click",
			"Cost Per Lead",
			"Customer Acquisition Cost",
			"Customer Churn Rate",
			"Customer Retention Metrics",
			"Demographic Market Segmentation",
			"Digital Marketing Metrics",
			"Display Advertising Metrics",
			"Earned Media Metrics",
			"Email Marketing Metrics",
			"Finance Metrics",
			"Geographic Market Segmentation",
			"Growth Metrics",
			"Lifetime Value",
			"Market Segmentation",
			"Marketing Analytics",
			"Marketing Data Collection",
			"Marketing KPIs",
			"Marketing Macro-Analytics",
			"Marketing Metrics",
			"Marketing Reports",
			"Online Analytical Processing",
			"Online Transaction Processing",
			"Paid Marketing Metrics",
			"Psychographic Market Segmentation",
			"Return on Investment",
			"Sales Metrics",
			"Search Engine Marketing Metrics",
			"Search Engine Optimization Metrics",
			"Service Level Metrics",
			"Social Media Marketing Metrics",
			"Time-Based Web Metrics",
			"Total Addressable Market",
			"UTM Codes",
			"Web Analytics",
			"Website Traffic Sources",
		],
		"Business Strategy": [
			"Website Traffic Sources",
			"Building Agile Teams",
			"Building AI Teams",
			"Building Data Science Teams",
			"Building Site Reliability Engineering Teams",
			"Business Process",
			"Data Science Roadmaps",
			"Data Science Strategy",
			"Digital Roadmaps",
			"Digital Talent Strategy",
			"Digital Transformation Awareness",
			"Digital Transformation Strategy",
			"GenAI Strategy",
			"Organizational Capability Building",
			"Organizational Change Management",
			"Organizational Skill Gap Analysis",
			"Technology Gap Analysis",
			"Value Proposition",
		],
		"Career Success": [
			"Value Proposition",
			"Behavioral Interviews",
			"Cover Letters",
			"Expressions of Interest",
			"Freelancing",
			"Freelancing Platforms",
			"GitHub Portfolios",
			"Job Interviews",
			"Online Presence",
			"Portfolio Websites",
			"Portfolios",
			"Professional Networking",
			"Resumes",
			"Social Media Presence",
			"UX Portfolios",
			"Whiteboarding Interviews",
		],
		"Contracts": [
			"Whiteboarding Interviews",
			"Non-Disclosure Agreements",
			"Scope of Work Documents",
			"Service Agreements",
			"Service Level Agreements",
		],
		"Decision Making and Problem Solving": [
			"Service Level Agreements",
			"Creative Problem Solving",
			"Decision Matrix Method",
			"Issue Trees",
			"Problem Solving",
			"Root Cause Analysis",
			"Structured Problem Solving Method",
			"Systems Thinking",
		],
		"Digital Marketing": [
			"Systems Thinking",
			"Bing Ads",
			"Conversion Rate Optimization",
			"Digital Marketing Awareness",
			"Digital Marketing Campaign Evaluation",
			"Digital Marketing Fluency",
			"Digital Marketing Strategy",
			"Display Advertising",
			"Email Campaign Calendars",
			"Email Contact Forms",
			"Email Marketing",
			"Email Marketing Content",
			"Facebook Ads",
			"Google Ads",
			"Keyword Lists",
			"Keyword Research",
			"Link Building",
			"Programmatic Display Advertising",
			"Search Engine Marketing",
			"Search Engine Optimization",
			"Search Text Ads",
			"SEO Audits",
			"Social Media Advertising",
			"Social Media Campaign Objectives",
			"Social Media Content",
			"Social Media Marketing",
			"Social Media Marketing Platforms",
			"User Targeting",
			"Video Advertising",
			"Video Marketing",
		],
		"Digital Mindset": [
			"Video Marketing",
			"Basic Computer Literacy",
			"Data Literacy Awareness",
			"Data Fluency",
			"Digital Culture",
			"Digital Technologies Knowledge",
			"Growth Mindset",
		],
		"Enterprise Architecture": [
			"Growth Mindset",
			"TOGAF Framework",
			"Zachman Framework",
		],
		"Finance and Accounting": [
			"Zachman Framework",
			"Adjusting for Corporate Actions",
			"Alpha Calculation",
			"Alpha Generation",
			"Alpha Research",
			"Alpha Signals",
			"Computing Technical Indicators",
			"Cost-Benefit Analysis",
			"ETFs",
			"Factor Investing",
			"Financial Indices",
			"Financial Markets",
			"Financial Modeling",
			"Financial Portfolio Optimization",
			"Financial Portfolio Risk Models",
			"Financial Portfolio Theory",
			"Financial Trading",
			"Freelance Pricing Frameworks",
			"GARCH Models",
			"Investment Performance Attribution",
			"Invoicing",
			"Price Behavior",
			"Quant Workflow",
			"Return Calculation",
			"Stock Return Factor Models",
			"Trading Signals",
			"Volatility Clustering",
		],
		"Leadership and People Management": [
			"Volatility Clustering",
			"Conflict Management",
			"Emotional Intelligence",
			"Leadership Styles",
			"Mentoring",
			"OKRs",
			"Organizational Capability Development",
			"Psychological Safety",
			"Strategic Thinking",
			"Team Dynamics",
			"Team Leadership",
			"Team SWOT Analysis",
		],
		"Marketing": [
			"Team SWOT Analysis",
			"Acquisition Channels",
			"Acquisition Funnels",
			"Acquisition Strategy",
			"Activation Tactics",
			"Agile Marketing",
			"Audience Evaluation",
			"Brand Design",
			"Branding Strategy",
			"Competitive Analysis",
			"Content Calendars",
			"Content Marketing",
			"Content Marketing Strategy",
			"Customer Journey Maps",
			"Customer Retention Tactics",
			"Growth Bottlenecks",
			"Growth Hacking",
			"Growth Loops",
			"Market Research",
			"Marketing Campaign ROI Maximization",
			"Marketing Channels",
			"Marketing Fluency",
			"Marketing Objectives",
			"Marketing Platforms",
			"Marketing Strategy",
			"Mixed Methods Market Research",
			"Network Effects",
			"Paid Marketing Channels",
			"Premium Value",
			"Product Channel Strategy",
			"Product Marketing",
			"Storytelling Frameworks for Marketing",
			"Target Personas",
		],
		"Personal Finance": [
			"Target Personas",
			"Bank Product and Financing Basics",
			"Finance and Technology",
			"Financial Data Security",
			"Personal Bank Account Basics",
			"Personal Budget Basics",
		],
		"Product Management": [
			"Personal Budget Basics",
			"Bug Triage",
			"Business Model Canvasses",
			"Cloud Product Management",
			"Coordination Activities Maps",
			"Feature Prioritization",
			"Feature Requests",
			"ICE Scoring Model",
			"Problem Validation",
			"Product Development Cycle",
			"Product Feature Usage Metrics",
			"Product Goals",
			"Product KPIs",
			"Product Launch",
			"Product Management Awareness",
			"Product Management Basics",
			"Product Proposals",
			"Product Requirements Documents",
			"Product Roadmaps",
			"Product Scaling",
			"Product Strategy",
			"Product Strategy Business Context",
			"Product Success Metrics",
			"Product Validation",
			"RICE Framework",
			"Technical Feasibility Evaluation",
		],
		"Product Monetization": [
			"Technical Feasibility Evaluation",
			"Product Financial Metrics",
			"Product Monetization Metrics",
			"Product Monetization Strategy",
			"Product Monetization Tactics",
			"Product Pricing Strategy",
		],
		"Professional Communication": [
			"Product Pricing Strategy",
			"Active Listening",
			"Blog Posts",
			"Communication Registers",
			"Communication Strategies",
			"Cross-Functional Collaboration",
			"Elevator Pitches",
			"End-User Documentation",
			"Evangelization",
			"Executive-Level Communication",
			"External Communications",
			"Feedback Loops",
			"Flowcharts",
			"Formal Written Communication",
			"Ghost Decks",
			"Meeting Facilitation",
			"Negotiation",
			"Persuasion",
			"Press Releases",
			"Problem Statements",
			"Product Proposals",
			"Professional Presentations",
			"Report Writing",
			"Roadmaps",
			"Stakeholder Analysis",
			"Stakeholder Engagement",
			"Stakeholder Identification",
			"Stakeholder Management",
			"Storytelling",
			"Technical Communication",
			"Thinking Hats",
			"Translating Business Requirements",
		],
		"Project and Program Management": [
			"Translating Business Requirements",
			"Data Project Management",
			"Digital Project Management Awareness",
			"Gantt Charts",
			"Prioritization",
			"Process Improvement",
			"Project Analytics",
			"Project Briefs",
			"Project Charters",
			"Project Cost Estimation",
			"Project Evaluation",
			"Project Execution",
			"Project Governance",
			"Project Initiation",
			"Project Initiation Documents",
			"Project Management",
			"Project Management Artifacts",
			"Project Management Frameworks",
			"Project Management Lifecycle",
			"Project Planning",
			"Project Risk Mitigation",
			"Project Scheduling",
			"Project Scoping",
			"Project Status Reporting",
			"RACI Matrices",
			"RAID Logs",
			"Requirements Gathering",
			"Social Capital",
			"Strategic Communication Plans",
			"Technical Debt Management",
			"Waterfall Project Management",
			"Work Breakdown Structures",
		],
		"Regulations, Standards, and Compliance": [
			"Work Breakdown Structures",
			"CCPA",
			"Child Privacy Regulations",
			"CIS Controls",
			"Computer Vision Benchmarks",
			"COPPA",
			"Cybersecurity Regulations and Standards",
			"Data Privacy Regulations",
			"DICOM",
			"Electronic Communications Regulations",
			"FDA Medical Device Framework",
			"Financial Privacy Regulations",
			"GDPR",
			"Healthcare Privacy Regulations",
			"HIPAA",
			"HITECH",
			"Medical and Healthcare Regulations and Standards",
			"Medical Code Sets",
			"NIST Cybersecurity Framework",
			"PCI-DSS",
			"Regional Privacy Regulations",
			"Right to be Forgotten",
			"SAE J3016 Levels of Driving Automation Standard",
			"WAI-ARIA",
			"WCAG",
			"Web Accessibility Standards",
		],
	},
	"Cloud Computing": {
		"Regulations, Standards, and Compliance": ["Web Accessibility Standards"],
		"Cloud Architecture": [
			"Web Accessibility Standards",
			"Cloud Architecture Model Types",
			"Cloud Architecture Proficiency",
			"Cloud Dependency Maps",
			"Cloud Design Principles",
			"Cloud Migration",
			"Infrastructure as a Service",
			"Microservices Architecture Basics",
			"Microservices Architecture Design",
			"Platform as a Service",
			"Refactoring from a Monolith",
			"Serverless Cloud Computing Architecture",
			"Strangler Pattern",
		],
		"Cloud Automation": [
			"Strangler Pattern",
			"Cloud Autoscaling",
			"Cloud Blueprints",
			"Cloud Pipeline Automation",
		],
		"Cloud Computing Fundamentals": [
			"Cloud Pipeline Automation",
			"Cloud Computing Awareness",
			"Cloud Computing Fluency",
			"Cloud Environment Configuration",
		],
		"Cloud Development": [
			"Cloud Environment Configuration",
			"Cloud Communication Protocols",
			"Cloud Computing Proficiency",
			"Cloud Engineering",
			"Infrastructure as Code",
			"Serverless Development",
		],
		"Cloud Performance and Reliability": [
			"Serverless Development",
			"Business Continuity Planning for Cloud",
			"Cloud Asset Deployment",
			"Cloud Availability",
			"Cloud Load Balancing",
			"Cloud Observability",
			"Cloud Performance Management",
			"Regional Cloud Asset Deployment",
		],
		"Cloud Scalability": [
			"Regional Cloud Asset Deployment",
			"Cloud Provisioning",
			"Cloud Resource Allocation",
			"Kubernetes Scaling",
			"Virtual Machine Management",
			"Virtualization for Cloud",
		],
		"Cloud Security": [
			"Virtualization for Cloud",
			"Cloud Asset Isolation",
			"Cloud Hardening Strategy",
			"Cloud Patch Management",
			"Cloud Security Fluency",
			"Cloud Security Strategy",
			"Container Vulnerability Management",
			"Docker Security",
			"Hybrid Cloud Security",
			"Image Hardening",
			"Image Signing",
			"Incident Response Planning for Cloud",
			"Kubernetes Security",
			"Microservices Hardening Test Plans",
			"Microservices Security",
		],
		"Cloud Strategy and Governance": [
			"Microservices Security",
			"Automated Cloud Cost Optimization",
			"Cloud Asset Management",
			"Cloud Capacity Management",
			"Cloud Capacity Planning",
			"Cloud Compliance",
			"Cloud Computing Business Context",
			"Cloud Cost Evaluation",
			"Cloud Cost Governance",
			"Cloud Cost Management",
			"Cloud Cost Policies",
			"Cloud Deployment Models",
			"Cloud Governance Strategy",
			"Cloud Migration Strategy",
			"Cloud Operational Efficiency",
			"Cloud Product Management",
			"Cloud Product Strategy",
			"Cloud Resource Provisioning",
			"Cloud ROI",
			"Cloud Solution Evaluation",
			"Distributed Cloud Computing",
			"Tiered Cloud Capacity Management",
		],
		"Containerization": [
			"Tiered Cloud Capacity Management",
			"Container Orchestration",
			"Containerization Fluency",
			"Containerization Proficiency",
		],
		"Hybrid Cloud": [
			"Containerization Proficiency",
			"Hybrid Cloud Automation",
			"Hybrid Cloud Design",
			"Hybrid Cloud Development",
			"Hybrid Cloud Security",
			"Hybrid cloud workload deployment",
		],
		"Private Cloud": [
			"Hybrid cloud workload deployment",
			"Private Cloud Configuration",
			"Private Cloud Infrastructure as a Service",
			"Private Cloud Platform as a Service",
			"Private Cloud Software as a Service",
			"VPC",
		],
	},
	"Computer Programming and Software Development": {
		"Private Cloud": ["VPC"],
		"Android Development": [
			"VPC",
			"Android Activities",
			"Android Activity Lifecycle",
			"Android App Audio",
			"Android App User Settings",
			"Android Best Practices",
			"Android Custom Views",
			"Android Development Basics",
			"Android Development Environment",
			"Android Development Proficiency",
			"Android Intents",
			"Android Notifications",
			"Android Property Animations",
			"Android UI Development",
			"Google Maps in Android Development",
			"RecyclerView",
		],
		"APIs": [
			"RecyclerView",
			"API Configuration",
			"API Deployment",
			"API Design",
			"API Development",
			"API Documentation",
			"API Awareness",
			"API Fluency",
			"API Management",
			"API Proficiency",
			"API Requests",
			"API Security",
			"API Testing",
			"API Troubleshooting",
			"B2B APIs",
			"Cybersecurity APIs",
			"REST APIs",
		],
		"Application Development": [
			"REST APIs",
			"Application Architecture",
			"Application Dependency Management",
			"Application Development Best Practices",
			"Application Development Proficiency",
			"Application State Management",
		],
		"Computer Graphics": [
			"Application State Management",
			"Bresenham's Line Algorithm",
			"CMYK Color Model",
			"Color Models",
			"Color Spaces",
			"Computer Graphics Proficiency",
			"Grayscale Color Model",
			"Image Gradient Calculation",
			"Ray Tracing",
			"RGB Color Model",
		],
		"Computer Science and Programming": [
			"RGB Color Model",
			"Abstraction",
			"Access Control Matrices",
			"Aspect-Oriented Programming",
			"Automatic Memory Allocation",
			"Bash",
			"Basic Computer Programming",
			"Binary Number Representation",
			"Boolean Expressions",
			"Buffer Overruns",
			"Call Stacks",
			"Call-by-Reference",
			"Call-by-Value",
			"Callbacks",
			"Coding Best Practices",
			"Command Line Interface Basics",
			"Command Line Tools",
			"Commenting Code",
			"Computer Memory Architecture",
			"Computer Memory Familiarity",
			"Computer Memory Management",
			"Computer Programming Awareness",
			"Computer Programming Proficiency",
			"Concurrent Computing",
			"Constraint Identification",
			"Constraint Reasoning",
			"Constraint Satisfaction Methods",
			"Constraint Satisfaction Problems",
			"Control Flow",
			"Data Binding",
			"Data Races",
			"Data Types in Programming",
			"Data Validation",
			"Dependency Injection",
			"Deterministic Data Testing",
			"Docstrings",
			"Dynamic Memory Allocation",
			"Errors and Exceptions",
			"Evaluation Strategies in Programming",
			"Event-Driven Programming",
			"File I/O",
			"Functional Programming",
			"Functional Programming Concepts",
			"Futures and Promises",
			"Generators",
			"Generic Programming",
			"gRPC",
			"Heap Memory",
			"Hexadecimal Numbers",
			"Immutable Data",
			"Intermediate Computer Programming",
			"Iterators",
			"l-values",
			"Lambda Expressions",
			"Linting",
			"Loops",
			"Magic Methods",
			"Memory Fragmentation",
			"Memory Leaks",
			"Memory-Efficient Programming",
			"Message Passing",
			"Message Queues",
			"Modular Code",
			"Non-Deterministic Data Testing",
			"Object-Document Mapping",
			"Object-Relational Mapping",
			"Ownership in Memory Management",
			"Parallel Computing",
			"PowerShell",
			"Programming Language Implementations",
			"Programming Language Type Systems",
			"Programming Paradigms",
			"r-values",
			"Race Conditions in Parallel Computing",
			"RAII",
			"Regular Expressions",
			"Resource Leaks",
			"Scripting",
			"Search Problems",
			"Segmentation Fault",
			"Shell Scripting",
			"Stack Memory",
			"Threading",
			"Uninitialized Memory Bugs",
			"UNIX Shell",
			"User Input Handling",
			"Variable Scope",
			"Virtual Memory",
		],
		"Cryptocurrency": [
			"Virtual Memory",
			"Bitcoin",
			"Bitcoin Core",
			"Blockchain",
			"Blockchain Awareness",
			"Blockchain Consensus",
			"Blockchain Oracles",
			"Blockchain Transactions",
			"Cryptocurrency Privacy and Security",
			"Cryptocurrency Tokens",
			"Dapps",
			"Decentralized Storage Protocol",
			"Ethereum",
			"Hardhat",
			"Hedera Client",
			"Hedera Consensus",
			"Hedera Tokens",
			"Private Blockchain",
			"Smart Contracts",
			"Solidity",
			"Testnets",
			"zk-SNARKs",
			"ZoKrates",
		],
		"Data Structures and Algorithms": [
			"ZoKrates",
			"2D Search Space Representation",
			"3D Search Space Representation",
			"A* Search Algorithm",
			"Algorithmic Notation (Big-O)",
			"Algorithmic Problem Solving",
			"Array Algorithms",
			"Backtracking Search",
			"Basic Algorithms",
			"Basic Data Structures and Algorithms",
			"Baum-Welch Algorithm",
			"Bellman Equation",
			"Breadth-First Search",
			"Computational Complexity",
			"Constraint Propagation",
			"Data Structures",
			"Data Structures and Algorithms Proficiency",
			"Depth-First Search",
			"Divide and Conquer Algorithms",
			"Dynamic Programming",
			"Extended Kalman Filters",
			"Gradient Descent",
			"Graph Algorithms",
			"Graph Data Structure",
			"Greedy Algorithms",
			"Hash Maps",
			"Hashing",
			"Hill Climbing",
			"Histogram Filters",
			"Informed Search",
			"Iterative Closest Point",
			"Iterative Policy Evaluation",
			"k-D Trees",
			"Kalman Filters",
			"Local Search",
			"Mathematical Optimization",
			"Matrix Factorization",
			"Minimax Search",
			"Monte Carlo Methods",
			"Normal Distributions Transform",
			"Occupancy Grid Mapping Algorithm",
			"Optimization Algorithms",
			"Pan-Tompkins algorithm",
			"Particle Filters",
			"Planning Algorithms",
			"Planning Graphs",
			"Policy Improvement",
			"Policy Iteration",
			"RANSAC Algorithm",
			"Recursive Algorithms",
			"Search Algorithms",
			"Simulated Annealing",
			"Sorting Algorithms",
			"State Space Search",
			"Tree Algorithms",
			"Tree Search",
			"Uniform Cost Search",
			"Uninformed Search",
			"Unscented Kalman Filters",
			"Value Iteration",
			"Viterbi Algorithm",
		],
		"DevOps": [
			"Viterbi Algorithm",
			"Basic Deployments",
			"Blue-Green Deployment",
			"Build Automation",
			"Canary Deployment",
			"CI/CD",
			"Continuous Deployment",
			"Continuous Integration",
			"Continuous Testing",
			"Declarative Manifests",
			"Deployment Automation",
			"Deployment Rollbacks",
			"Deployment Testing",
			"DevOps Awareness",
			"DevOps Basics",
			"DevOps Business Context",
			"DevOps Documentation",
			"DevOps Fluency",
			"DevOps Proficiency",
			"DevSecOps",
			"Feature Launch Reviews",
			"GitOps",
			"Logging",
			"Rolling Deployments",
			"Template Manifests",
		],
		"Disaster Recovery": [
			"Template Manifests",
			"Backup Strategy",
			"Business Continuity Automation",
			"Business Continuity Playbooks",
			"Disaster Recovery Plans",
			"IT Incident Management",
			"Recovery Point Objective",
			"Recovery Time Objective",
		],
		"Front-End and Web Development": [
			"Recovery Time Objective",
			"Apple App Transport Security Protocol",
			"Application Metrics",
			"Application Routing",
			"Application Servers",
			"Basic Web Development",
			"Bootstrap",
			"Content Management System Fluency",
			"Cross-Browser Development",
			"CSS",
			"CSS Preprocessors",
			"CSS-in-JS",
			"DevTools",
			"DOM Events",
			"DOM Manipulation",
			"Express Web Framework",
			"Fetching Data",
			"Flask",
			"Flexbox",
			"Front-End Development Basics",
			"HTML",
			"HTML Template Creation",
			"LESS",
			"Local Development",
			"Microservices",
			"Parsing Form Data",
			"Responsive App Design",
			"SASS",
			"Service Workers",
			"SOAP",
			"The Document Object Model",
			"Web Development",
			"Web Forms",
			"Web Services",
			"Website Performance Optimization",
		],
		"iOS Development": [
			"Website Performance Optimization",
			"iOS Affordances",
			"iOS Animations",
			"iOS Concurrency",
			"iOS Core Data",
			"iOS Gestures",
			"iOS SplitView Navigation",
			"iOS Stack Navigation",
			"iOS Tab Navigation",
			"iOS UI Development",
			"iOS View Hierarchy",
		],
		"Mobile App Development": [
			"iOS View Hierarchy",
			"App Localization",
			"Location-Aware App Development",
			"Mobile App Stores",
			"Mobile App Styling",
			"Mobile Data Management",
			"Mobile OS Patterns",
			"Offline Caching",
		],
		"Object-Oriented Programming": [
			"Offline Caching",
			"Access Specifiers",
			"Classes",
			"Encapsulation",
			"Inheritance",
			"Object Creation Design Patterns",
			"Object-Oriented Programming Basics",
			"Object-Oriented Programming Proficiency",
			"UML",
		],
		"Quantum Computing": [
			"UML",
			"Quantum Computing Awareness",
			"Quantum Computing Fluency",
		],
		"Search Engines": ["Quantum Computing Fluency", "Search Engine Basics"],
		"Site Reliability Engineering": [
			"Search Engine Basics",
			"Application Monitoring",
			"Observability Dashboards",
			"Reliability Risk Assessment",
			"Service Level Dashboards",
			"Service Level Indicators",
			"Service Level Objectives",
			"Site Reliability Engineering Best Practices",
			"Site Reliability Engineering Business Context",
			"Site Reliability Metrics",
			"Synthetic Monitoring",
			"Toil Reduction",
		],
		"Software Architecture and System Design": [
			"Toil Reduction",
			"Agile Integration",
			"Distributed Computing",
			"Distributed Data Processing",
			"Distributed Data Storage",
			"Event-Driven Architecture",
			"Integration Architecture",
			"Self-Healing System Design",
			"Service Oriented Architecture",
			"Software Architecture",
			"Software Integrations",
			"Streaming Architectures",
			"Tactical Integration",
		],
		"Software Design Patterns": [
			"Tactical Integration",
			"Behavioral Design Patterns",
			"Creational Design Patterns",
			"Design Pattern Fundamentals",
			"Design Pattern Proficiency",
			"Inversion of Control",
			"Model-View-Controller",
			"Model-View-Viewmodel Architecture",
			"Multitier Architecture",
			"Object-Oriented Design Patterns",
			"Repository Design Pattern",
			"Structural Design Patterns",
		],
		"Software Development Processes": [
			"Structural Design Patterns",
			"As-Built Documents",
			"Back-End Development",
			"Behavior-Driven Development",
			"Code Refactoring",
			"Code Reviews",
			"Data Versioning",
			"Feature Design Documents",
			"Git",
			"Git Commit Messages",
			"Object-Oriented Analysis and Design",
			"README Files",
			"Release Notes",
			"Software Development Automation",
			"Software Development Lifecycle",
			"Software Development Proficiency",
			"Software Pipelines",
			"Software Project Documentation",
			"Software Project Organization",
			"Test-Driven Development",
			"Version Control",
		],
		"Software Monitoring and Troubleshooting": [
			"Version Control",
			"API Troubleshooting",
			"Application Tracing",
			"Code Debugging",
			"Microservices Debugging",
		],
		"Software Quality Assurance": [
			"Microservices Debugging",
			"Automation Testing",
			"Behavioral Software Testing",
			"Code Coverage",
			"Espresso Testing Framework",
			"Functional Testing",
			"Fuzzing",
			"Happy Path Testing",
			"Integration Testing",
			"Mobile App Testing",
			"Negative Testing",
			"Software Load Testing",
			"Software Performance Testing",
			"Software Testing",
			"Test Automation",
			"Test Environments",
			"Unit Testing",
		],
	},
	"Cybersecurity": {
		"Software Quality Assurance": ["Unit Testing"],
		"Application Security": [
			"Unit Testing",
			"Application Authentication",
			"Application Authorization",
			"Application Code Vulnerabilities",
			"Application Security Basics",
			"Application Security Best Practices",
			"Auth0",
			"Database Query Sanitization",
			"I/O Sanitization",
			"Image Layer Analysis",
			"JWTs",
			"Secure Firmware Updates",
			"Software Bill of Materials",
			"Software Composition Analysis",
			"Static Application Security Testing",
		],
		"Cloud Security": [
			"Static Application Security Testing",
			"Cloud Asset Isolation",
			"Cloud Hardening Strategy",
			"Cloud Patch Management",
			"Cloud Security Fluency",
			"Cloud Security Strategy",
			"Container Vulnerability Management",
			"Docker Security",
			"Hybrid Cloud Security",
			"Image Hardening",
			"Image Signing",
			"Incident Response Planning for Cloud",
			"Kubernetes Security",
			"Microservices Hardening Test Plans",
			"Microservices Security",
		],
		"Cybersecurity Implementation": [
			"Microservices Security",
			"Antivirus Definition Update Pipelines",
			"API Security",
			"Authentication",
			"Authorization",
			"Basic Cybersecurity Implementation",
			"Chroot Jails",
			"CIA Triad",
			"Cybersecurity Awareness",
			"Cybersecurity Controls",
			"Cybersecurity Fluency",
			"Cybersecurity Framework Implementation",
			"Cybersecurity Segregation of Duties",
			"Cybersecurity Trust Models",
			"Cybersecurity TTPs",
			"DevSecOps",
			"Digital Footprint Analysis",
			"Distributed Denial-of-Service Protection",
			"Email Security",
			"Endpoint Security",
			"External Threat Mitigation",
			"Intelligence-Driven Security",
			"Internal Threat Mitigation",
			"IOC Management",
			"Mobile Device Management",
			"Non-Repudiation",
			"Offensive Security",
			"Operating System Hardening",
			"Perimeter Security",
			"Port Scanning",
			"Public Key Certificate Management",
			"Public Key Certificates",
			"Public Key Infrastructure",
			"Route Based VPN",
			"Scalable Security Services",
			"Security Assessment",
			"Security Auditing",
			"Security Devices",
			"Security Information and Event Management",
			"Security Patch Management",
			"Security Risk Classification",
			"Security Risk Mitigation",
			"Security Risk Remediation",
			"Security Services Integration",
			"Shift-Left Testing",
			"Systems Hardening",
			"Systems Security",
			"Threat Actors",
			"Threat Hunting",
			"Threat Intelligence",
			"Threat Mitigation",
			"Threat Modeling",
			"Threat Profiling",
			"Unix OS Hardening",
			"Value-Based Security Risk Assessment",
			"Virtual LAN",
			"VPN",
			"Vulnerability Assessment",
			"Vulnerability Lifecycle",
			"Vulnerability Management",
			"Vulnerability Mitigation",
			"Vulnerability Patching",
			"Vulnerability Research",
			"Vulnerability Scanning",
			"Web Application Firewalls",
			"Web Application Vulnerability Scanning",
			"YARA Rules",
		],
		"Cybersecurity Incident Response": [
			"YARA Rules",
			"Cybersecurity Incident Containment",
			"Cybersecurity Incident Remediation",
			"Cybersecurity Incident Response Automation",
			"Cybersecurity Incident Response Playbooks",
			"Cybersecurity Threat Triage",
		],
		"Cybersecurity Monitoring": [
			"Cybersecurity Threat Triage",
			"Cybersecurity Alert Enrichment",
			"Cybersecurity Alerts",
			"Exploit Detection",
			"File Integrity Monitoring",
			"IT Continuous Monitoring",
			"Network Monitoring",
			"Runtime Security Monitoring",
			"Webhook Security Alerts",
		],
		"Cybersecurity Policy and Strategy": [
			"Webhook Security Alerts",
			"Control Systems Hardening Strategy",
			"Cybersecurity Business Context",
			"Cybersecurity Compliance",
			"Cybersecurity Governance",
			"Cybersecurity GRC",
			"Cybersecurity Policy Writing",
			"Cybersecurity Risk Management",
			"Cybersecurity Strategy",
			"Cybersecurity Training Strategies",
			"Data Security Policy Writing",
			"Device Hardening Strategy",
			"Hardening Strategy",
			"Server Hardening Strategy",
			"Threat-Driven Security",
		],
		"Cybersecurity Resources, Standards, and Frameworks": [
			"Threat-Driven Security",
			"CIS Benchmarks",
			"CVE",
			"CVSS",
			"Cyber Kill Chain Model",
			"Cybersecurity Advisories",
			"Cybersecurity Resource Fluency",
			"Cybersecurity Standards Fluency",
			"DiD Framework",
			"ExploitDB",
			"ISO 27001",
			"MITRE ATT&CK",
			"NIST 800-series",
			"NIST NVD",
			"Open Source Vulnerability Database",
			"OWASP",
			"OWASP Top-10",
			"OWASP WSTG",
			"SABSA Framework",
			"STRIDE Framework",
			"Zero Trust Security Model",
		],
		"Data Security": [
			"Zero Trust Security Model",
			"Cryptography",
			"Data at Rest",
			"Data Encryption",
			"Data Exfiltration",
			"Data in Transit",
			"Data Security for Cloud",
			"Data Security Fundamentals",
			"Database Security",
			"Pepper",
			"PII",
			"Salt",
		],
		"Ethical Hacking": [
			"Salt",
			"Active Cybersecurity Reconnaissance",
			"Advanced Persistent Threat",
			"Adversarial Simulation",
			"Automated Penetration Testing",
			"Backdoors",
			"Brute Force Attacks",
			"Cyber Attack Persistence",
			"Cybersecurity Pivoting",
			"Cybersecurity Reconnaissance",
			"Digital Footprint Removal",
			"Exploit Code Execution",
			"Google Hacking",
			"Keystroke Logging",
			"Malware Development",
			"On-Premise Cyber Attacks",
			"Open-Source Intelligence",
			"Passive Cybersecurity Reconnaissance",
			"Password Attacks",
			"Penetration Testing",
			"Phishing",
			"Privilege Escalation",
			"Red Teaming",
			"Router Hacking",
			"Semi-Automated Penetration Testing",
			"Service Enumeration",
			"Social Engineering",
			"SQL Injection",
			"Steganography",
			"Vulnerability Exploitation",
			"Web Hacking",
		],
		"Identity and Access Management": [
			"Web Hacking",
			"Access Control Matrices",
			"Access Control Models",
			"Access Management",
			"Attribute-Based Access Control",
			"Conditional Access",
			"Credential Management",
			"IAM Policies",
			"IAM Restrictions",
			"IAM Roles",
			"IAM Users",
			"Identity and Access Management Fundamentals",
			"Mandatory Access Control",
			"Multi-Factor Authentication",
			"Principle of Least Privilege",
			"Privileged Identity Management",
			"Remote Access Management",
			"Role-Based Access Control",
		],
		"Network Security": [
			"Role-Based Access Control",
			"Firewall Configuration",
			"Firewall Rules",
			"Firewalls",
			"Host-Based IDSs",
			"Intrusion Detection Systems",
			"Intrusion Prevention",
			"Intrusion Protection Systems",
			"IPv6 Security",
			"Microsoft Domain Isolation Policy Design",
			"Network Access Control Lists",
			"Network Attack Vectors",
			"Network Security Best Practices",
			"Network Security Fundamentals",
			"Network Security Proficiency",
			"Network Security Reports",
			"Network Taps",
			"Network Traffic Capture",
			"Packet Analysis",
			"Packet Capture",
			"Port Mirroring",
		],
		"Privacy Engineering": [
			"Port Mirroring",
			"Data Anonymization",
			"Data Minimization",
			"Data Privacy Classification",
			"Data Privacy Fundamentals",
			"Data Privacy Principles",
			"k-anonymization",
			"Obfuscation for Data Minimization",
			"Privacy by Design Framework",
			"Privacy Engineering for Compliance",
			"Privacy Risk Assessment",
			"Redaction for Data Minimization",
			"Tiers of Deletion",
		],
		"Security Architecture": [
			"Tiers of Deletion",
			"Secure Application Architecture Design",
			"Secure Network Architecture Design",
			"Security Architecture Fundamentals",
		],
	},
	"Data and Analytics": {
		"Security Architecture": ["Security Architecture Fundamentals"],
		"Big Data": [
			"Security Architecture Fundamentals",
			"Big Data Business Context",
			"Big Data Fluency",
			"Big Data Processing",
			"Big Data Proficiency",
			"Big Data Storage",
			"Data Streaming",
			"Data Streaming Schemas",
			"HDFS",
			"Streaming Data Stores",
		],
		"Data Analysis": [
			"Streaming Data Stores",
			"Analytic Frameworks",
			"Analytic Methodology Maps",
			"Data Analysis Awareness",
			"Data Analysis Process",
			"Data Enrichment",
			"Data Limitations and Biases",
			"Data Pre-Processing",
			"Data Problem Definition",
			"Data Profiling",
			"Data Quality Assessment",
			"Data Types",
			"Differencing of Time-Series Data",
			"ETS Models",
			"Explanatory Data Analysis",
			"Exploratory Data Analysis",
			"Historical Data Analysis",
			"Link Analysis",
			"Predictive Analytics Awareness",
			"Predictive Analytics",
			"Qualitative Data Analysis",
			"Quantitative Data Analysis",
			"Sequential Data Analysis",
			"Time-Series Analysis",
			"Time-Series Forecasting",
			"Time-Series Forcasting Basics",
			"Univariate Time-Series Analysis",
		],
		"Data and Analytics Business Context": [
			"Univariate Time-Series Analysis",
			"Data Analysis Business Context",
			"Data Consumers",
			"Data Use-Cases",
			"Time-Series Forecasting Business Context",
		],
		"Data Architecture": [
			"Time-Series Forecasting Business Context",
			"Data and Data Architecture Strategy",
			"Data Architecture Fluency",
			"Data Infrastructure Basics",
			"Data Lake Design Patterns",
			"Data Lake Management",
			"Data Lakes",
			"Data Producers",
			"Data Storage",
			"Data Warehouse Architecture",
			"Data Warehouse Management",
			"Data Warehousing",
			"Database Flexibility",
			"Database Scalability",
			"Denormalized Data Schemas",
			"OLAP Cubes",
			"Online Analytical Processing Models",
			"Online Transactional Processing Models",
			"Operational Data Store Models",
			"Snowflake Schemas",
			"Star Schemas",
		],
		"Data Automation": [
			"Star Schemas",
			"Batch Processing",
			"Stream Processing",
			"Stream Processing Use Cases",
			"Timeframing in Stream Processing",
			"Windowing in Stream Processing",
		],
		"Data Engineering": [
			"Windowing in Stream Processing",
			"CRISP-DM",
			"Data Cleaning",
			"Data Extraction",
			"Data Gathering",
			"Data Ingestion",
			"Data Integration",
			"Data Loading",
			"Data Mining",
			"Data Pipeline Creation",
			"Data Pipeline DAGs",
			"Data Pipeline Design",
			"Data Pipeline Maintenance",
			"Data Pipeline Partitioning",
			"Data Pipelines",
			"Data Preparation",
			"Data Scraping",
			"Data Transformation",
			"Data Wrangling",
			"Data Wrangling Fundamentals",
			"ELT",
			"ETL",
		],
		"Data Exchange": [
			"ETL",
			"Base64",
			"Data Deserialization",
			"Data Encoding",
			"Data Serialization",
			"DTOs",
			"JSON",
		],
		"Data Formats": [
			"JSON",
			"Data Format Fundamentals",
			"Medical Imaging Data Formats",
			"NIfTI",
		],
		"Data Governance": [
			"NIfTI",
			"Data Cataloging",
			"Data Dictionaries",
			"Data Governance Awareness",
			"Data Governance Business Context",
			"Data Governance Fluency",
			"Data Lifecycle Management",
			"Data Lineage",
			"Data Quality Control",
			"Master Data Management",
			"Master Data Management Systems",
			"Metadata Management",
			"Metadata Management Systems",
			"Sensitive Data Tracking",
		],
		"Data Modeling": [
			"Sensitive Data Tracking",
			"Conceptual ERDs",
			"Crow's Foot Notation",
			"Data Modeling Basics",
			"Enterprise Data Models",
			"ERDs",
			"Event Data Models",
			"Logical ERDs",
			"NoSQL Data Models",
			"Physical ERDs",
			"Relational Data Models",
			"Types of Data",
		],
		"Data Presentation": [
			"Types of Data",
			"Advanced Data Visualizations",
			"Animated Data Visualizations",
			"Basic Data Visualizations",
			"Categorical Data Visualization",
			"Chart Selection",
			"Chart Types",
			"Data Storytelling",
			"Data Visualization",
			"Data Visualization Business Context",
			"Data Visualization Design",
			"Explanatory Data Visualization",
			"Exploratory Data Visualization",
			"Forecast Visualization",
			"Qualitative Data Visualization",
			"Quantitative Data Visualization",
			"Vector Visualization",
		],
		"Data Science": [
			"Vector Visualization",
			"Data Science Awareness",
			"Data Science Business Context",
			"Data Science Fluency",
			"Data Science Models and Algorithms",
			"Data Science Operations",
			"Data Science Use-Cases",
		],
		"Databases": [
			"Data Science Use-Cases",
			"3rd Normal Form",
			"ACID Properties",
			"Business Rule Enforcement in Databases",
			"CAP Theorem",
			"Column-Oriented DBMSs",
			"CRUD Model",
			"Data Definition",
			"Data Manipulation",
			"Data Normalization",
			"Data Recovery",
			"Data Replication",
			"Data Schemas",
			"Data Staging",
			"Database Backup Automation",
			"Database Denormalization",
			"Database Design",
			"Database Frameworks",
			"Database Fundamentals",
			"Database Geo-Replication",
			"Database Indexing",
			"Database Normalization",
			"Database Performance",
			"Document Database Schemas",
			"Foreign Keys",
			"Log Shipping",
			"NoSQL",
			"Query Plans",
			"RDBMS Performance and Optimization",
			"Relational Database Basics",
			"Relational Database Migration",
			"Relational Database Proficiency",
			"Relational Database Transactions",
			"Row-Oriented DBMSs",
			"Table Design",
			"Table Partitioning",
			"Vector Databases",
		],
		"Spreadsheets": [
			"Vector Databases",
			"Advanced Spreadsheet Use",
			"Basic Spreadsheet Use",
			"Cell Management in Spreadsheets",
			"Data Validation in Spreadsheets",
			"Data Visualization in Spreadsheets",
			"Forecast Modeling in Spreadsheets",
			"Intermediate Spreadsheet Use",
			"Pivot Tables",
			"Spreadsheet Automation",
			"Spreadsheet Functions",
		],
	},
	"IT Infrastructure and Support": {
		"Spreadsheets": ["Spreadsheet Functions"],
		"Computer Networking": [
			"Spreadsheet Functions",
			"Client-Server Model",
			"Computer Networking Basics",
			"CORS",
			"cURL",
			"Golden Images",
			"HTTP",
			"HTTPS",
			"Network Administration",
			"Network Segmentation",
			"Network Topologies",
			"NSLookup",
			"Port Forwarding",
			"Secure Network Requests",
			"Serial Terminal Processing",
			"TCP/IP",
			"WebSocket",
		],
		"IT Architecture": ["WebSocket", "Architecture Diagramming"],
		"System and Application Monitoring": [
			"Architecture Diagramming",
			"Webhook Alerts",
		],
		"Systems Administration": [
			"Webhook Alerts",
			"IT Asset Consolidation",
			"IT Asset Inventories",
			"IT Asset Management",
			"Patch Management",
			"Systems Administration Proficiency",
		],
		"Technical Support": [
			"Systems Administration Proficiency",
			"Hardware Installation",
			"Hardware Troubleshooting",
			"IT Helpdesk",
			"Network Hardware Maintenance",
			"On-Call Best Practices",
			"Remote Technical Support",
			"Software Installation",
			"Software Troubleshooting",
			"Technical Troubleshooting",
		],
		"Wireless Technology": [
			"Technical Troubleshooting",
			"3GPP",
			"5G Technology",
			"5G Fluency",
			"General Packet Radio Service",
			"Radio Access Network",
			"Radio Equipment",
			"Wireless System Design",
		],
	},
	"Mathematics, Logic, and Science": {
		"Wireless Technology": ["Wireless System Design"],
		"Algebra": [
			"Wireless System Design",
			"Elementary Algebra",
			"Linear Algebra",
			"Linear Combination",
			"Linear Mapping",
			"Matrix Multiplication",
			"Matrix Operations",
			"Quaternions",
			"Rotation Matrices",
			"State Transformations",
			"Systems of Linear Equations",
			"Tensors",
			"Vector Addition",
			"Vector Scaling",
			"Vectors",
		],
		"Arithmetic": ["Vectors", "Basic Arithmetic", "Logarithm and Exponentiation"],
		"Biology": ["Logarithm and Exponentiation", "Basic Heart Physiology"],
		"Calculus": [
			"Basic Heart Physiology",
			"Basic Calculus",
			"Chain Rule Application",
			"Continuous Functions",
			"Coordinate Transformation",
			"Derivatives",
			"Differential Calculus",
			"Finding Derivatives",
			"Implicit Differentiation",
			"Integral Calculus",
			"Integrals",
			"Jacobians",
			"Limits of functions",
			"Linear Functions",
			"Multivariable Calculus",
			"Vector Calculus",
		],
		"Discrete Mathematics": [
			"Vector Calculus",
			"Discrete Mathematics Proficiency",
			"Graph Theory",
		],
		"Game Theory": ["Graph Theory", "AlphaZero", "Markov Games", "Shapley Value"],
		"Geometry": ["Shapley Value", "Basic Geometry", "Euler Angles"],
		"Healthcare": [
			"Euler Angles",
			"Clinical Basics",
			"Electrocardiographs",
			"Medical Imaging Basics",
		],
		"Logic": [
			"Medical Imaging Basics",
			"First Order Logic",
			"Logical Reasoning",
			"Logic Circuits",
			"Logic Gates",
			"Propositional Logic",
		],
		"Physics": [
			"Propositional Logic",
			"Basic Physics",
			"Classical Mechanics",
			"Quadrotor Dynamics",
			"Voltage and Resistance",
		],
		"Probability and Statistics": [
			"Voltage and Resistance",
			"Advanced Probability",
			"Basic Descriptive Statistics",
			"Basic Probability",
			"Bayes' Theorem",
			"Bayesian Inference",
			"Bayesian Networks",
			"Bayesian Probability",
			"Bayesian Statistics",
			"Conditional Probability",
			"Gaussian Distribution",
			"Indexing in Statistics",
			"Inferential Statistics",
			"Intermediate Probability",
			"Latent Variables",
			"Law of Total Probability",
			"Markov Decision Processes",
			"Normal Distribution",
			"Outlier Analysis",
			"Probability Distribution",
			"Random Sampling",
			"Root-Mean-Square Error",
			"Sample Testing",
			"Similarity Score",
			"Standard Score",
			"Statistical Rigor",
			"Statistical Sampling",
			"Statistical Significance",
			"Statistics Proficiency",
			"Window Functions",
		],
		"Statistical Modeling": [
			"Window Functions",
			"ARIMA",
			"ARMA",
			"Basic Statistical Modeling",
			"Binary Classification Models",
			"Class Imbalance",
			"Classification Models",
			"Cluster Models",
			"Cluster Validation",
			"Curve Fitting",
			"DBSCAN",
			"Decision Trees",
			"Euclidean Clustering",
			"Gradient Boosting",
			"Hidden Markov Models",
			"Hierarchical Clustering Models",
			"Intermediate Statistical Modeling",
			"K-Means Clustering",
			"Least Squares",
			"Likelihood Function",
			"Linear Models",
			"Linear Regression",
			"Logistic Regression",
			"Markov Models",
			"Model Cross-Validation",
			"Non-Binary Classification Models",
			"Overfitting Prevention",
			"Random Forest Models",
			"Single Linkage Clustering",
			"Statistical Modeling Fundamentals",
			"Statistical Modeling Proficiency",
			"Statistical Regression",
			"Stepwise Regression",
			"Tree-Based Models",
		],
		"Trigonometry": [
			"Tree-Based Models",
			"Basic Trigonometry",
			"Cosine",
			"Fourier Transforms",
			"Pythagorean Theorem",
			"Sine",
		],
	},
	"Programming Languages and Frameworks": {
		"Trigonometry": ["Sine"],
		"C#": ["Sine", "C# Proficiency"],
		"C++": [
			"C# Proficiency",
			"Basic C++",
			"C++ Bitwise Operations",
			"C++ Classes",
			"C++ Code Optimization",
			"C++ Constants",
			"C++ Control Flow",
			"C++ Copy and Move Semantics",
			"C++ Data Structures",
			"C++ Data Types",
			"C++ File Handling",
			"C++ for Robotics",
			"C++ Functions",
			"C++ Header Files",
			"C++ Inheritance",
			"C++ Libraries",
			"C++ Pointers",
			"C++ Polymorphism",
			"C++ Proficiency",
			"C++ Standard Library",
			"C++ Syntax",
			"C++ User Input",
			"C++ Vectors",
			"Eigen Library",
			"Intermediate C++",
			"Memory Management in C++",
			"Point Cloud Library",
			"Rule of Five",
			"Rule of Three",
			"Search Algorithms in C++",
			"Smart Pointers",
		],
		"Go": [
			"Smart Pointers",
			"Go Arrays",
			"Go Conditionals",
			"Go Functions",
			"Go Interfaces",
			"Go Loops",
			"Go Maps",
			"Go Range",
			"Go Slices",
			"Go Structs",
			"Go Variables",
		],
		"Java": [
			"Go Variables",
			"Basic Java",
			"Control Flow in Java",
			"DAOs",
			"Date and Time in Java",
			"Hibernate ORM",
			"Intermediate Java",
			"Java Annotations",
			"Java Arrays",
			"Java Assertions",
			"Java Best Practices",
			"Java Collections",
			"Java Data Structures",
			"Java Data Types",
			"Java Documentation",
			"Java EE",
			"Java Enums",
			"Java Exception Handling",
			"Java Files API",
			"Java Generics",
			"Java Inheritance",
			"Java Interfaces",
			"Java Methods",
			"Java Modules",
			"Java Package Management",
			"Java Proficiency",
			"Java Reflection",
			"Java Standard Library",
			"Java Stream API",
			"Java Streams",
			"Java String Methods",
			"Java Subclasses",
			"Java Syntax",
			"Java Testing",
			"Java Tools",
			"Java Type Casting",
			"JDBC",
			"JLink",
			"JPA",
			"JPQL",
			"JRE",
			"JShell",
			"JUnit",
			"MyBatis",
			"Regular Expressions in Java",
			"Servlets",
			"SLF4J",
			"SQL in Java",
		],
		"JavaScript": [
			"SQL in Java",
			"Angular CLI",
			"Angular Components",
			"Angular Directives",
			"Angular Router",
			"Angular Templates",
			"AngularJS",
			"Application State Management with Redux",
			"Arrays in JavaScript",
			"Asynchronous JavaScript",
			"Asynchronous Redux",
			"Basic JavaScript",
			"Control Flow in JavaScript",
			"Ember",
			"Functional JavaScript",
			"Functional JavaScript Libraries",
			"Idiomatic Redux",
			"IIFEs",
			"Intermediate JavaScript",
			"Jasmine",
			"JavaScript Async/Await",
			"JavaScript Composition",
			"JavaScript Data Structures",
			"JavaScript Data Types",
			"JavaScript Event Loop",
			"JavaScript Exception Handling",
			"JavaScript Functions",
			"JavaScript Methods",
			"JavaScript Object Methods",
			"JavaScript Package Management",
			"JavaScript Performance",
			"JavaScript Proficiency",
			"JavaScript Promises",
			"JavaScript Syntax",
			"JavaScript Variables",
			"Jest",
			"JSX",
			"Mockito",
			"Node-Postgres",
			"NodeJS",
			"NodeJS Environment Variables",
			"Object-Oriented JavaScript",
			"React-Redux Bindings",
			"Redux",
			"Redux Actions",
			"Redux Design Patterns",
			"Redux Integration",
			"Redux Middleware",
			"Redux Reducers",
			"Redux Store API",
			"Redux Stores",
			"Redux Toolkit",
			"Redux-Thunk",
			"The JavaScript Call Stack",
			"VueJS",
		],
		"Markup Languages": ["VueJS", "Declarative XML", "XML"],
		"MATLAB": ["XML", "MATLAB Proficiency"],
		"Python": [
			"MATLAB Proficiency",
			"AI algorithms in Python",
			"Anaconda",
			"Basic Python",
			"BeautifulSoup",
			"Built-in Python Functions",
			"Control Flow in Python",
			"cvxpy",
			"Functional Python",
			"Intermediate Python",
			"Jupyter Notebooks",
			"List Comprehension",
			"Matplotlib",
			"NiBabel",
			"NumPy",
			"Object-Oriented Python",
			"Pandas",
			"PEP8",
			"Pillow",
			"pip",
			"psycopg2",
			"PyCaret",
			"PyDicom",
			"Pylint",
			"PyTest",
			"Python Arrays",
			"Python Best Practices",
			"Python Classes",
			"Python Collections",
			"Python Data Analysis Libraries",
			"Python Data Structures",
			"Python Data Types",
			"Python Decorator Functions",
			"Python Documentation",
			"Python Exception Handling",
			"Python for Data Science",
			"Python Function Definition",
			"Python Functions",
			"Python IDEs",
			"Python Library Fluency",
			"Python Lists",
			"Python Methods",
			"Python Modules",
			"Python Namespaces",
			"Python Operators",
			"Python Package Management",
			"Python Packaging",
			"Python Proficiency",
			"Python Scripting",
			"Python Standard Library",
			"Python String Methods",
			"Python Syntax",
			"Python Testing",
			"Python Trees",
			"Python Turtle",
			"Python Variables",
			"Python Virtual Environments",
			"Pythonic Design Patterns",
			"Search Implementation in Python",
			"SQLAlchemy",
			"Text Processing in Python",
			"Theano",
			"unittest",
		],
		"Query Languages": ["unittest", "DAX", "GraphQL"],
		"R": [
			"GraphQL",
			"Basic R",
			"Control Flow in R",
			"R Data Structures",
			"R Function Definition",
			"R Proficiency",
			"R Syntax",
		],
		"React": [
			"R Syntax",
			"Basic React",
			"Create React App",
			"React Component State",
			"React Data Management",
			"React Design Patterns",
			"React Development",
			"React Hooks",
			"React Lifecycle",
			"React Native",
			"React Native AsyncStorage",
			"React Native Basics",
			"React Native Components",
			"React Native Development Environment",
			"React Native Features",
			"React Native Forms",
			"React Native Interactive Features",
			"React Native Navigation",
			"React Native OS APIs",
			"React Native Storage",
			"React Native StyleSheet API",
			"React Native Styling",
			"React Proficiency",
			"React Router",
			"React Styling",
		],
		"Ruby": ["React Styling", "Ruby Proficiency"],
		"Rust": [
			"Ruby Proficiency",
			"Concurrency in Rust",
			"Control Flow in Rust",
			"Documentation in Rust",
			"Ownership and Borrowing in Rust",
			"Rust Advanced Types",
			"Rust Basics",
			"Rust Cargo and Crates",
			"Rust Data Types",
			"Rust Error Handling",
			"Rust FFI",
			"Rust Functions and Modules",
			"Rust Macros",
			"Testing in Rust",
			"Traits and Generics in Rust",
		],
		"Scala": ["Traits and Generics in Rust", "Scala Proficiency"],
		"Serialization Formats": ["Scala Proficiency", "XML"],
		"Spring Framework": [
			"XML",
			"SpEL",
			"Spring Boot",
			"Spring Boot Configuration",
			"Spring Data JPA",
			"Spring Managed Components",
			"Spring MVC",
			"Spring Proficiency",
			"Spring Security",
		],
		"SQL": [
			"Spring Security",
			"Advanced SQL",
			"Basic SQL",
			"Data Definition Language",
			"Data Manipulation Language",
			"Intermediate SQL",
			"KSQL",
			"SQL Aggregations",
			"SQL CRUD Commands",
			"SQL JOINs",
			"SQL Proficiency",
			"SQL Queries",
			"SQL Query Performance Tuning",
			"SQL Scripts",
			"SQL Subqueries",
			"SQL Window Functions",
		],
		"Swift": [
			"SQL Window Functions",
			"AVFoundation Framework",
			"Basic Swift",
			"Network Requests in Swift",
			"String Manipulation in Swift",
			"Swift and Objective-C Interoperability",
			"Swift Arrays",
			"Swift AutoLayout",
			"Swift Class Extensions",
			"Swift Classes",
			"Swift Closures",
			"Swift Collections",
			"Swift Constants",
			"Swift Data Persistence",
			"Swift Data Structures",
			"Swift Data Types",
			"Swift Dictionaries",
			"Swift Enums",
			"Swift File Management",
			"Swift Functions",
			"Swift Grand Central Dispatch",
			"Swift Inheritance",
			"Swift Methods",
			"Swift NSUserDefaults",
			"Swift Operators",
			"Swift Optionals",
			"Swift Proficiency",
			"Swift Properties",
			"Swift Protocols",
			"Swift Queues",
			"Swift Sets",
			"Swift Structs",
			"Swift Syntax",
			"SwiftData",
			"SwiftData Migrations",
			"SwiftData Operations",
			"SwiftUI",
		],
		"TypeScript": [
			"SwiftUI",
			"Basic TypeScript",
			"TypeScript Async/Await",
			"TypeScript Development",
			"TypeScript Exception Handling",
			"TypeScript Proficiency",
			"TypeScript Promises",
			"TypeScript Setup",
			"TypeScript Syntax",
			"TypeScript Typing",
		],
		"Visual Basic .NET": ["TypeScript Typing", "VB.NET String Methods"],
	},
	"Research and Design": {
		"Visual Basic .NET": ["VB.NET String Methods"],
		"Accessibility": [
			"VB.NET String Methods",
			"Accessible User Experience Design",
			"RTL",
			"Talkback",
		],
		"Application Design": [
			"Talkback",
			"Application Animations",
			"Application Visual Design",
			"Multi-Screen App Design",
			"Single-Screen App Design",
		],
		"Experimentation": [
			"Single-Screen App Design",
			"A/B Testing",
			"Bias Detection",
			"Experiment Control",
			"Experiment Design",
			"Experiment Metrics",
			"Interpreting Test Results",
			"Multivariate Testing",
			"SMART Experiments",
		],
		"User Experience and Product Design": [
			"SMART Experiments",
			"Clickable Prototypes",
			"Crazy 8s",
			"Design Annotation",
			"Design Ethics",
			"Design Optimization",
			"Design Systems",
			"Design Thinking Awareness",
			"Design Thinking",
			"Double Diamond Design Model",
			"Empathy Maps",
			"Guerilla Design Sprints",
			"High Fidelity Prototypes",
			"Human-Centered Design",
			"Ideation",
			"Iterative Product Design",
			"Low Fidelity Prototypes",
			"Product Design",
			"Product Design Principles",
			"Product Design Sprints",
			"Product Prototyping",
			"Product Storyboarding",
			"Production-Ready Assets",
			"Rapid Prototyping",
			"Solution Sketching",
			"UI Design",
			"UI Kits and Plugins",
			"User Journey Maps",
			"User Personas",
			"UX Design Awareness",
			"UX Design Principles",
			"UX Friction",
			"Wireframes",
		],
		"User Research": [
			"Wireframes",
			"Jobs to be Done Framework",
			"Affinity Mapping",
			"Beta Testing",
			"Focus Groups",
			"Heuristic Evaluations",
			"How Might We Method",
			"Prototype Testing",
			"Qualitative User Research",
			"Quantitative User Research",
			"Real-world Testing",
			"Remote User Testing",
			"Research Repositories",
			"Surveys",
			"Usability Testing",
			"User Interviews",
			"User Research Planning",
			"User Testing",
		],
		"Visual Design": [
			"User Testing",
			"2D Animation",
			"Application Visual Design",
			"Digital Arts Fluency",
			"Digital Design",
			"Digital Image Editing",
			"Digital Video Editing",
			"Mood Boards",
			"User-Friendly Visual Design",
			"Visual Design Principles",
			"Visual Design Elements",
			"Visual Style Guides",
		],
		"Web Design": [
			"Visual Style Guides",
			"Landing Pages",
			"Responsive Web Design",
			"Web design for SEO",
			"Website Layout",
		],
	},
	"Software and Hardware": {
		"Web Design": ["Website Layout"],
		"AI and Machine Learning Tools": [
			"Website Layout",
			"3D Slicer",
			"Aequitas",
			"DVC",
			"Google AutoML",
			"IBM Watson",
			"Intel DevCloud",
			"Keras",
			"MicroDicom",
			"MLFlow",
			"Multi-Backend Keras",
			"Open Neural Network Exchange",
			"OpenCV",
			"Waymo LiDAR Specifications",
			"Waymo Open Dataset",
			"Weights & Biases",
		],
		"Amazon SageMaker": [
			"Weights & Biases",
			"Data Loading with SageMaker",
			"DeepAR Forecasting Algorithm",
			"Distributed Model Training with SageMaker",
			"Model Deployment with SageMaker",
			"SageMaker API Gateway",
			"SageMaker Autopilot",
			"SageMaker Autoscaling",
			"SageMaker Batch Transform Jobs",
			"SageMaker Built-In Algorithms",
			"SageMaker Clarify",
			"SageMaker Data Wrangler",
			"SageMaker Debugger",
			"SageMaker Familiarity",
			"SageMaker Feature Store",
			"SageMaker Ground Truth",
			"SageMaker Jumpstart",
			"SageMaker Logs",
			"SageMaker Model Endpoints",
			"SageMaker Model Monitor",
			"SageMaker Pipelines",
			"SageMaker Processing",
			"SageMaker Proficiency",
			"SageMaker Studio Notebooks",
			"SageMaker Training Jobs",
		],
		"Amazon Web Services": [
			"SageMaker Training Jobs",
			"Amazon Athena",
			"Amazon CloudWatch",
			"Amazon DynamoDB",
			"Amazon ECR",
			"Amazon ECS",
			"Amazon Elastic Compute Cloud",
			"Amazon Elastic Kubernetes Service",
			"Amazon EMR",
			"Amazon GuardDuty",
			"Amazon Inspector",
			"Amazon RDS",
			"Amazon S3",
			"Amazon Simple Notification Service",
			"Amazon VPC",
			"Amazon Web Services Basics",
			"Amazon Web Services Setup",
			"AWS Autoscaling",
			"AWS Availability Zones",
			"AWS CLI",
			"AWS CloudFormation",
			"AWS CloudTrail",
			"AWS CodeBuild",
			"AWS CodePipeline",
			"AWS Compute Services",
			"AWS Config",
			"AWS Cost Explorer",
			"AWS Data Lakes",
			"AWS Data Warehouse",
			"AWS Database Services",
			"AWS Development",
			"AWS Elastic Beanstalk",
			"AWS Encryption SDK",
			"AWS Familiarity",
			"AWS Glue",
			"AWS IAM",
			"AWS Key Management Service",
			"AWS Lambda",
			"AWS Networking Services",
			"AWS Proficiency",
			"AWS Scalability Services",
			"AWS Secrets Manager",
			"AWS Security Hub",
			"AWS Server migration",
			"AWS Step Functions",
			"AWS Storage Services",
			"AWS Systems Manager Agent",
			"AWS VPN",
			"AWS WAF",
			"Cloud security in AWS",
			"Data encryption in AWS",
			"DevSecOps in AWS",
			"Redshift",
		],
		"Analytics and Data Visualization Tools": [
			"Redshift",
			"Alteryx",
			"Excel",
			"Flourish",
			"Google Data Studio",
			"Grafana",
			"Plotly",
			"SAS",
		],
		"Android Development Tools": ["SAS", "Kotlin"],
		"Apache Kafka": [
			"Kotlin",
			"Confluent Kafka Python Client",
			"Kafka Basics",
			"Kafka Connect",
			"Kafka Performance Monitoring",
			"Kafka Proficiency",
			"Kafka REST Proxy",
			"Kafka Schema Registry",
			"KSQL",
		],
		"API Tools": [
			"KSQL",
			"FastAPI",
			"OpenAPI",
			"Postman",
			"RetroFit",
			"Swagger",
			"Webhooks",
			"Wiremock",
		],
		"Autonomous Vehicles and Robots": [
			"Wiremock",
			"Accelerometers",
			"Autonomous Vehicle Sensor Selection",
			"Barometers",
			"Gazebo",
			"gmapping ROS Package",
			"Gyroscopes",
			"IMUs",
			"LiDAR",
			"LiDAR Sensors",
			"LiDAR Simulator",
			"LiDAR Technical Specifications",
			"Magnetometers",
			"Odometers",
			"PX4 Autopilot",
			"QGroundControl",
			"Quadrotor Control Systems",
			"Quadrotor Hardware Components",
			"Radar",
			"Robot Operating System",
			"ROS Adaptive MCL Package",
			"ROS EKF Package",
			"ROS Nodes",
			"TurtleBot",
		],
		"AWS Machine Learning Tools": [
			"TurtleBot",
			"AWS DeepComposer",
			"AWS DeepLens",
			"AWS DeepRacer",
			"Figure Eight",
		],
		"Azure AI Services": [
			"Figure Eight",
			"Azure Cognitive Search",
			"Azure Cognitive Search Data Import",
			"Azure Cognitive Search Indexers",
			"Azure Cognitive Search Queries",
			"Azure Cognitive Services",
			"Azure Conversational AI",
			"Azure Conversational AI Agents",
			"Azure ML Automated ML",
			"Azure ML Designer",
			"Azure ML Experiments",
			"Azure ML Pipelines",
			"Azure ML Platform",
			"Azure ML SDK",
			"Azure ML User Management",
			"Azure Text Analytics",
			"Microsoft Bot Framework",
		],
		"Big Data Tools": [
			"Microsoft Bot Framework",
			"Apache Avro",
			"Apache Hive",
			"Apache Spark",
			"Faust",
			"Hadoop",
		],
		"Business Intelligence Tools": ["Hadoop", "Business Intelligence Software"],
		"Cloud Software and Services": [
			"Business Intelligence Software",
			"Cloud Foundry",
			"Cloudera",
			"Docker",
			"Docker-bench",
			"DockerHub",
			"Grype",
			"Jaeger",
			"Kube-bench",
			"Kubernetes",
			"Packer",
			"Prometheus",
			"Syft",
			"Terraform",
			"Trivy",
		],
		"Computer Hardware": ["Trivy", "CPUs", "FPGAs", "GPUs", "VPUs"],
		"Content Management Systems": [
			"VPUs",
			"Drupal",
			"HubSpot CMS Hub",
			"Joomla",
			"Magento",
			"Shopify",
			"Squarespace",
			"Wix",
			"WordPress",
		],
		"Cybersecurity Tools": [
			"WordPress",
			"Burp Suite",
			"Clam AntiVirus",
			"Cloud Security Software",
			"dig",
			"DIRB",
			"GoPhish",
			"Hash Cat",
			"John the Ripper",
			"Kali Linux",
			"Maltego",
			"Metasploit",
			"Nessus",
			"Netdiscover",
			"Nikto",
			"Nmap",
			"OSINT Tools",
			"Osquery",
			"OWASP Zap",
			"Snort IDS",
			"SOAR Platforms",
			"SQLmap",
			"Sysdig Falco",
			"traceroute",
			"Veil-Evasion",
			"Wireshark",
			"WPscan",
		],
		"Data Automation Tools": ["WPscan", "Apache Airflow"],
		"Data Management Tools": [
			"Apache Airflow",
			"Informatica",
			"Informatica PowerCenter",
			"Power Query",
		],
		"DevOps Tools": [
			"Power Query",
			"Ansible",
			"ApacheBench",
			"Argo CD",
			"CircleCI",
			"Helm",
			"Jenkins",
			"Splunk",
		],
		"Diagramming Tools": ["Splunk", "Draw.io", "Lucidchart"],
		"Digital Design Tools": [
			"Lucidchart",
			"Adobe Creative Suite",
			"Adobe Illustrator",
			"Adobe Photoshop",
			"Adobe XD",
			"Balsamiq",
			"Canva",
			"DaVinci Resolve",
			"Figma",
			"Photopea",
			"Prototyping Tools",
			"Sketch",
			"Synfig Studio",
		],
		"Embedded Systems and Internet of Things": [
			"Synfig Studio",
			"Camera Calibration",
			"CAN Bus",
			"Control Systems",
			"Debugging Embedded Systems",
			"Device Drivers",
			"Embedded system communication protocols",
			"Embedded System Communication Protocol basics",
			"GPS",
			"I2C",
			"Interrupt Handling",
			"IoT Proficiency",
			"LIN Bus",
			"MQTT",
			"Output Displays",
			"Sensor Calibration",
			"Sensors",
			"SPI",
			"Smart Wearables",
			"UART",
		],
		"GitHub": [
			"UART",
			"Basic GitHub",
			"GitHub Actions",
			"GitHub Branches",
			"GitHub Collaboration",
			"GitHub Copilot",
			"GitHub Proficiency",
		],
		"Google Analytics": [
			"GitHub Proficiency",
			"Advanced Displays in Google Analytics",
			"Channel Customization in Google Analytics",
			"Filtering in Google Analytics",
			"Google Analytics Acquisition Reports",
			"Google Analytics Alerts",
			"Google Analytics Annotations",
			"Google Analytics Attribution Reports",
			"Google Analytics Audience Reports",
			"Google Analytics Custom Reports",
			"Google Analytics Dashboards",
			"Google Analytics Dimensions",
			"Google Analytics Ecommerce Reports",
			"Google Analytics Event Management",
			"Google Analytics Explorations",
			"Google Analytics Fundamentals",
			"Google Analytics Goals",
			"Google Analytics Metrics",
			"Google Analytics Proficiency",
			"Google Analytics Reports",
			"Google Analytics Settings",
			"Google Analytics User Management",
			"Segmentation in Google Analytics",
		],
		"Google Cloud Platform": [
			"Segmentation in Google Analytics",
			"Gemini API",
			"Google AI Studio",
			"Google Cloud BigQuery",
			"Google Cloud Dataflow",
			"Google Cloud Development",
			"Google Cloud Looker",
			"Google Cloud Platform Proficiency",
			"Vertex AI",
			"Vertex AI Studio",
		],
		"Google Workspace": [
			"Vertex AI Studio",
			"Gemini",
			"Gmail",
			"Google Calendar",
			"Google Chat",
			"Google Docs",
			"Google Drive",
			"Google Forms",
			"Google Meet",
			"Google Sheets",
			"Google Slides",
		],
		"Graph Databases": ["Google Slides", "Amazon Neptune", "Neo4j"],
		"Image Capture Tools": ["Neo4j", "Cameras", "Digital Cameras"],
		"iOS Development Tools": ["Digital Cameras"],
		"Martech": [
			"Digital Cameras",
			"Email Marketing Tools",
			"Hootsuite",
			"MailChimp",
			"Social Media Marketing Tools",
		],
		"Microsoft Azure": [
			"Social Media Marketing Tools",
			"Application Authentication with Azure",
			"Application Monitoring with Azure",
			"Azure Active Directory",
			"Azure AD Connect",
			"Azure API endpoints",
			"Azure API Management",
			"Azure App Service",
			"Azure Architecture",
			"Azure Automation",
			"Azure Autoscale",
			"Azure Fundamentals",
			"Azure Bastion",
			"Azure Batch",
			"Azure blob storage",
			"Azure Blueprints",
			"Azure CLI",
			"Azure Compute Service",
			"Azure Conditional Access Policies",
			"Azure Container Registry",
			"Azure CosmosDB",
			"Azure Data Services",
			"Azure Database Migration Service",
			"Azure datasets",
			"Azure datastores",
			"Azure Defender",
			"Azure Desired State Configuration",
			"Azure Development",
			"Azure Event Grid",
			"Azure Form Recognizer",
			"Azure functions",
			"Azure Insights",
			"Azure Key Vault",
			"Azure Kubernetes Service",
			"Azure Load Balancing Services",
			"Azure Log Analytics",
			"Azure Logic Apps",
			"Azure Migrate",
			"Azure Model and Data Deletion",
			"Azure Model and Data Export",
			"Azure Monitor",
			"Azure Network Security Groups",
			"Azure Network Watcher",
			"Azure Networking Services",
			"Azure Pipelines",
			"Azure Portal",
			"Azure Pricing Calculator",
			"Azure Resource Groups",
			"Azure Resource Manager",
			"Azure Security Center",
			"Azure Sentinel",
			"Azure Service Principals",
			"Azure Site Recovery",
			"Azure Smart Alerts",
			"Azure Total Cost of Ownership Calculator",
			"Azure User Management",
			"Azure Video Analyzer",
			"Azure Virtual Machine Backup",
			"Azure Web Application Firewall",
			"Cloud Security in Azure",
			"Model Deployment with Azure",
			"Model Training with Azure",
			"Network Security with Azure",
			"Resource Hardening with Azure",
			"SQL databases in Azure",
		],
		"NoSQL Databases": [
			"SQL databases in Azure",
			"CassandraDB",
			"CQL",
			"MongoDB",
			"Redis",
		],
		"Nutanix": [
			"Redis",
			"Nutanix AHV",
			"Nutanix Beam",
			"Nutanix Calm",
			"Nutanix Prism",
		],
		"OpenVINO": [
			"Nutanix Prism",
			"Deep Learning Workbench",
			"OpenVINO Deployment Manager",
			"OpenVINO Heterogeneous Plugin",
			"OpenVINO Inference Engine",
			"OpenVINO Model Optimizer",
			"OpenVINO Multi-Device Plugin",
		],
		"Operating Systems": [
			"OpenVINO Multi-Device Plugin",
			"Basic Linux",
			"iOS",
			"Linux",
			"Linux Command Line Interface",
			"Linux Filesystem Hierarchy Standard",
			"Operating System Familiarity",
			"Windows Administration",
			"Windows Operating System",
		],
		"Power BI": [
			"Windows Operating System",
			"Power BI Basics",
			"Power BI Calculated Columns and Measures",
			"Power BI Data Pipeline",
			"Power BI Data Types",
			"Power BI Get Data",
			"Power BI Proficiency",
			"Power BI Report Customization",
			"Power BI Report Design",
		],
		"Project Management Software": [
			"Power BI Report Design",
			"JIRA",
			"Trello",
			"Workflow Management Software",
		],
		"Relational Database Management Systems": [
			"Workflow Management Software",
			"Alembic",
			"Microsoft SQL Server",
			"PostgreSQL",
			"RDBMS Proficiency",
			"SQLite",
		],
		"Sales and Marketing Tools": [
			"SQLite",
			"Customer Relationship Management Software",
			"Salesforce",
		],
		"Search Engine Optimization Tools": ["Salesforce", "Moz"],
		"Software Build Tools": [
			"Moz",
			"Apache Ant",
			"CMake",
			"Gradle",
			"Heroku",
			"Java Build Tools",
			"Make",
			"Maven",
			"Travis CI",
			"Webpack",
		],
		"Software Development Tools": [
			"Webpack",
			"Android Studio",
			"Apache JMeter",
			"ESLint",
			"FireBase",
			"Glide",
			"HashiCorp Vagrant",
			"IDEs",
			"Intel VTune Amplifier",
			"IntelliJ",
			"Java IDEs",
			"JavaScript Console",
			"JDK",
			"Prettier",
			"Selenium",
			"Thymeleaf",
			"Visual Studio IDE",
		],
		"System Modeling and Architecting Tools": [
			"Visual Studio IDE",
			"ER/Studio Data Architect",
			"erwin Data Modeler",
			"OpenText ProVision",
			"PowerDesigner",
			"System Architect",
		],
		"Tableau": [
			"System Architect",
			"Tableau Calculated Fields",
			"Tableau Data Pane",
			"Tableau Field Organization and Customization",
			"Tableau Groups",
			"Tableau Hierarchies",
			"Tableau Interactive Dashboards",
			"Tableau Map-Based Visualizations",
			"Tableau Pages",
			"Tableau Proficiency",
			"Tableau Sets",
			"Tableau Storypoint",
			"Tableau Visualizations",
		],
		"UIKit": [
			"Tableau Visualizations",
			"UIButton",
			"UIImagePickerController",
			"UIKit Classes",
			"UILabel",
			"UISwitch",
			"UITableView",
			"UIViews",
		],
		"UiPath": [
			"UIViews",
			"Control Flow in UiPath",
			"UiPath Activities",
			"UiPath Anchors",
			"UiPath Arguments",
			"UiPath Collections",
			"UiPath Data Scraping Wizard",
			"UiPath Data Tables",
			"UiPath Data Types",
			"UiPath Excel Automation",
			"UiPath Exception Handling",
			"UiPath Image Automation",
			"UiPath Mail Automation",
			"UiPath Orchestrator",
			"UiPath PDF Activities",
			"UiPath Recording",
			"UiPath Robots",
			"UiPath Screen Scraping Wizard",
			"UiPath Selectors",
			"UiPath Setup",
			"UiPath Studio",
			"UiPath Text Automation",
			"UiPath Variables",
		],
		"Word Processing and Note Taking Tools": [
			"UiPath Variables",
			"CherryTree",
			"Google Docs",
			"Microsoft Word",
		],
		"XCode IDE": [
			"Microsoft Word",
			"Swift IBActions",
			"Swift IBOutlets",
			"XCode IDE Basics",
		],
	},
}
